apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - name: project-service
          image: project-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: project-service-env
---
apiVersion: v1
kind: Secret
metadata:
  name: project-service-env
type: Opaque
data:
  DB_HOST: cHJvamVjdC1zZXJ2aWNlLXBvc3RncmVz
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_NAME: dXNlcnM=
  DB_PORT: NTQzMg==
  JWT_SECRET_KEY: bXlzZWNyZXRrZXk=

  # Use  kubectl port-forward svc/user-service 8080:8080  to port forward requests