apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-service-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
