apiVersion: v1
kind: Service
metadata:
  name: project-service-postgres
spec:
  selector:
    app: project-service-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
