apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service-postgres
  template:
    metadata:
      labels:
        app: task-service-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: task-service-env
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: task-service-env
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: task-service-env
                  key: DB_NAME
