services:
  task-service:
    build:
      context: .
    image: task-service:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - task-service-postgres
    restart: always
    networks:
      - manaflo-network
  
  task-service-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "task_service"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - manaflo-network

networks:
  manaflo-network:
    driver: bridge