apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          imagePullPolicy: IfNotPresent
          resources:
              requests:
                cpu: "100m"       
                memory: "64Mi"     
              limits:
                cpu: "500m"        
                memory: "128Mi"    
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: user-service-env
---
apiVersion: v1
kind: Secret
metadata:
  name: user-service-env
type: Opaque
data:
  DB_HOST: dXNlci1zZXJ2aWNlLXBvc3RncmVz 
  DB_USER: cm9vdA==
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_NAME: dXNlcnM=
  DB_PORT: NTQzMg==
  JWT_SECRET_KEY: bXlzZWNyZXRrZXk=

  # Use  kubectl port-forward svc/user-service 8080:8080  to port forward requests